### ISSUE TITLE
도메인 연결 및 API 구현

### ISSUE THREAD

**Issue by cocahack** [cocahack/codesquad-link-archive#12]
### Description

배포된 API Gateway를 Cloudflare의 DNS와 연동하여 쉬운 url을 사용할 수 있도록 변경해야 한다. 프론트엔드 작업을 하기 전에, 각 리소스를 가져오기 위한 람다 함수를 구현한다.

### TODO
- [ ] API Gateway를 Cloudflare와 연결
- [ ] 유저 목록 API
- [ ] 채널 목록 API
- [ ] 날짜 별 링크 목록 API
